### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by andk** [net-amqp-rabbitmq/net-amqp-rabbitmq#11]
When I run tests repeatedly I seem to be able to get fails occasionally. First I thought a hash randomization issue but then I saw another fail with 5.12.5 which was way before hash randomization struck.

Sample fail report:

5.12.5 005_noack.t: http://www.cpantesters.org/cpan/report/8b956b8e-f5fa-11e3-889a-63660a370852

5.20.0 003_consume.t: http://www.cpantesters.org/cpan/report/50060588-f5fa-11e3-9a60-26d40a370852

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by manchicken** [comment]
Almost everything I've seen on cpantesters looks like it's sporadic connectivity issues to dev.rabbitmq causing failures.

Do you have a link to a specific failure? I wonder if this is arch-specific.

**Comment by andk** [comment]
The point is that statistics are then helpful when not too many influences come together. So to get the most out of them it's good to fix the first bug you know about and then watch the results for the improved code to discover new patterns. We now have a situation that we know that a good portion of the fails is explained by the rounding bug explained above. It seems like a good strategy would be to fix only this one known bug first and then look what we can identify  among the remaining fails.

Having said that, here is a fail that has its cause in a connectivity problem:

http://www.cpantesters.org/cpan/report/49826801

**Comment by manchicken** [comment]
I was asking about a link to one with the rounding issue, sorry. If you have a test which could consistently replicate this bug I'd be happy to troubleshoot it further, but I have yet to encounter this one.

Also, could you please tell me which version you're using when you encounter this bug? In 0.007001 I completely reworked type mapping between Perl and AMQP types.

**Comment by andk** [comment]
I'm sorry, I misunderstood you. Here is the statistics page:

http://analysis.cpantesters.org/reports_by_field?distv=Net-AMQP-RabbitMQ-0.007001;field=conf%3Auselongdouble

All tests with uselongdouble=define have fails, e.g. the oldest one is http://www.cpantesters.org/cpan/report/47834854

**Comment by manchicken** [comment]
Gotcha! This is a bug which only appears under Perl with long doubles
defined. I missed that part. Thanks.

I'm working on some protocol level stuff now, this will be next after I
finish that. The protocol level thing may go all the way back to the C
library we bind against, not sure. I hope to finish that this month and
release a bunch of smaller stuff like this in February.

Much thanks!

**Comment by markwellis** [comment]
is this fixed now with the 64bit stuff?

**Comment by manchicken** [comment]
Are we still seeing this issue? I haven't seen this pop up in CPAN for a while.

**Comment by andk** [comment]
>>>>> On Sat, 17 Oct 2015 19:55:12 -0700, "Michael D. Stemle, Jr." <notifications@github.com> said:

  > Are we still seeing this issue? I haven't seen this pop up in CPAN
  > for a while.

Current version is according to metacpan 1.200000:

https://metacpan.org/release/Net-AMQP-RabbitMQ

When you click on the link on the left side "Testers", you see that
1.200000 is mostly red:

http://matrix.cpantesters.org/?dist=Net-AMQP-RabbitMQ+1.200000

If you click on the link "analysis" at the bottom of the page you get
at:

http://analysis.cpantesters.org/solved?distv=Net-AMQP-RabbitMQ-1.200000

If you click on the link on the table about "uselongdouble" you find
that currently all nine test reports for 1.200000 that come from a
uselongdouble perl are FAILs:

http://analysis.cpantesters.org/reports_by_field?distv=Net-AMQP-RabbitMQ-1.200000;field=conf%3Auselongdouble

(columns are sortable)

The reports listed in this table are clickable, e.g.

http://www.cpantesters.org/cpan/report/61127431

If you scroll to the failing test you find

#   Failed test 'payload'
#   at t/023_numeric_header_fields.t line 54.
#     Structures begin differing at:
#          $got->{props}{headers}{double} = '3.14100000000000001'
#     $expected->{props}{headers}{double} = '3.141'
# Looks like you failed 1 test of 12.

So I would say, it's still there.

Sorry for bringing bad news,
HTH && Thanks,
-- 
andreas

**Comment by manchicken** [comment]
I'm sorry you think this is bad news. Sometimes a question is just a
question. :-)

I'll look at this again when I get online again. I may be looking at
integer precision again, I'm playing with the module on raspbian as well.
