### ISSUE TITLE
recv error when using rabbitmq federation 

### ISSUE THREAD

**Issue by lukexue** [net-amqp-rabbitmq/net-amqp-rabbitmq#45]
upstream
--------(A)---federation---(B)--------
msg-->|--------fanout------ |fanout
(recv)..ok........................ /fail : Unsupported Perl type >t< at index 2 
(get)....ok........................./fail : Unexpected header 1! 

RabbitMQ 3.4.4, Erlang 17.1 / Net-AMQP-RabbitMQ-0.100000

**Comment by manchicken** [comment]
I'm sorry, I don't understand the problem. Could you please go over this again with more detail, and provide sample code for how to replicate the issue?

**Comment by lukexue** [comment]
The program happen when using rabbitmq federation. 
A(source) ---federation-->  B(destination)  
fanout exchange

insert message from A server will trans data to A,B
and
it is ok when using recv/get function at A server 
it show error message when using recv/get function at B server

the error message is Unsupported Perl type >t< at index 2 / Unexpected header 1!

**Comment by lukexue** [comment]
#!/usr/bin/perl
use utf8;
use Encode;
use JSON::XS;
use Net::AMQP::RabbitMQ;
my $mq = Net::AMQP::RabbitMQ->new();
eval { $mq->connect( "127.0.0.1", { user => "luke", password => "vmxxxxx", timeout => 30 } ); };
if ($@) {
	exit;
}
$mq->channel_open(1);
$mq->exchange_declare(
	1,
	'test.10.0.0.5',
	{
		exchange_type => 'fanout',    #default 'direct'
		durable       => 1,           #default 0
		auto_delete   => 0,           #default 1
	}
);


my $qn = $mq->queue_declare(
	1,
	'queue.127.0.0.1',
	{
		durable     => 1,    #default 0
		auto_delete => 0,    #default 1
	}
);


$mq->queue_bind( 1, $qn, 'test.10.0.0.5', '' );
$mq->consume( 1, $qn , { 'no_ack' => 0 });

while (1) {
	my $rv;
        eval { $rv = $mq->recv(); };
        if ($@){
        	print $@ . "\n";
        	exit;
        }
		if ( ref( $rv->{$k} ) eq 'HASH' ) {

		}
		else {

			if ( $k eq 'body' ) {
				my $body = $rv->{$k};
				if ( Encode::is_utf8($body) ) {
					$body = encode( 'utf-8', $body );
				}
                print $body;
			} elsif ( $k eq 'delivery_tag' )
			{
				$mq->ack( 1, $rv->{$k} );
			}
		}
}

**Comment by manchicken** [comment]
What is `$k`? I think I'm missing some of the code.

**Comment by lukexue** [comment]
I have modified the code. I think rabbitmq federation mechanism is the key point. Because i run the same code in the two side. Just another server(B) will get error message.

**Comment by manchicken** [comment]
Okay, are you able to replicate this on the dev.rabbitmq.com server?

**Comment by lukexue** [comment]
I can not replicate this on  the dev.rabbitmq.com server. Because just have one server here(can not setup federation). Do you need prepare same environment to test for you?

**Comment by manchicken** [comment]
If you could prepare this for me using publicly available credentials, that'd be great. Ideally all tests we do could be repeatable and usable by all users perpetually into the future, but if you have a specific plugin or configuration then we will try our best to support it.

If we don't have a publicly available test environment against which we can test with those extensions, we cannot promise support for those extensions. I'll try my best, I just can't promise it.

**Comment by lukexue** [comment]
Hello~
I have setup the server and wrote testing code for the problem. Could you give me the email address. I will send an mail to you. Thanks.

**Comment by hazelBobins** [comment]
This should be real simple to fix. The issue is that the redeliver bit/bool is set, and in mq_table_to_hashref the case statement does not check for the 'AMQP_FIELD_KIND_BOOLEAN' case i.e. 't' and hence croaks

**Comment by manchicken** [comment]
@hazelBobins: wouldn't that be something we could replicate without Federation?

**Comment by markwellis** [comment]
@manchicken didn't you add handling around AMQP_FIELD_KIND_BOOLEAN the other day? is this fixed now?

**Comment by manchicken** [comment]
I did. I still don't know how to replicate this issue, so I'm not sure.

**Comment by markwellis** [comment]
meh, i'll close it then, if it's still there @lukexue can you reopen it thanks
